apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadtkqo6534-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadtkqo6534-tenant-component
    app.kubernetes.io/part-of: loadtkqo6534-tenant-app
  name: loadtkqo6534-tenant-component
  namespace: loadtkqo6534-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadtkqo6534-tenant-component
    weight: null
status: {}
